[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "geometry/@IdealDetector@"
detectors_file_updated = "geometry/SPS_Nov_2022/prealigned_@RunNumber@_threshold_seed5.5.conf" 
histogram_file         = "prealignment_@RunNumber@_threshold_seed5.5.root"
number_of_events = @NumberOfEvents@
output_directory="output/SPS_Nov_Physics/run@RunNumber@/"

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
#eudaq_loglevel = INFO
file_name = "@DataDir@/run@RunNumber@.raw"
n_samples_baseline_opamp = 96		#OPAMP DAQ
minimum_sampling_frame_opamp = 98	#OPAMP DAQ
maximum_sampling_frame_opamp = 101	#OPAMP DAQ
n_samples_baseline_scope_opamp = 100 #OPAMP SCOPE number of points on which compute the baseline
n_signal_samples_scope_opamp = 50 #OPAMP SCOPE
shifting_from_t0 = 700
delay_from_t0 = 850
threshold_cut_t0_finder = 7
n_points_t0_finder = 10

[ClusteringSpatial]
type = "ALPIDE"
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = true

[ClusteringAnalog]
type="OPAMP"
threshold_seed=5.5
threshold_neighbor=5.5
method="cluster"
seeding_method=max

[Correlations]

[Prealignment]
damping_factor=1
method = gauss_fit
fit_range_rel = 50 
max_correlation_rms=6mm
time_cut_abs = 1e99
