[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"


detectors_file         = "geometry/SPS_Nov_2022/prealigned_@RunNumber@_threshold_seed5.5.conf" 
detectors_file_updated = "geometry/SPS_Nov_2022/aligned_@RunNumber@.conf"			
histogram_file         = "telescope_alignment_@RunNumber@.root"
number_of_events = @NumberOfEvents@
output_directory="output/SPS_Nov_Physics/run@RunNumber@/"	

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
n_samples_baseline_opamp = 96		#OPAMP DAQ
minimum_sampling_frame_opamp = 98	#OPAMP DAQ
maximum_sampling_frame_opamp = 101	#OPAMP DAQ
n_samples_baseline_scope_opamp = 100 #OPAMP SCOPE number of points on which compute the baseline
n_signal_samples_scope_opamp = 50 #OPAMP SCOPE
shifting_from_t0 = 700
delay_from_t0 = 850
threshold_cut_t0_finder = 7
n_points_t0_finder = 10


[ClusteringSpatial]
type = "ALPIDE"
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = false


[ClusteringAnalog]
type="OPAMP"
threshold_seed=5.5
threshold_neighbor=5.5
method="cluster"
seeding_method=max

[Correlations]

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 10mm,10mm
min_hits_on_track    = 8
exclude_dut          = false
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_5", "ALPIDE_6", "ALPIDE_7","OPAMP_3","OPAMP_4"
momentum             = 120GeV
unique_cluster_usage = true  # only use a cluster for one track. In case of multiple assignment, the track with the best chi2/ndof is kept. Default to falsed
reject_by_roi        = true
max_plot_chi2        = 100    # default to 50

[AlignmentMillepede]
residual_cut         = 0.1mm
residual_cut_init    = 1mm
iterations           = 3
dofs                 = true, true, false, false, false, true
sigmas               = 50um, 50um, 50um, 0.005rad, 0.005rad, 0.005rad
exclude_dut          = false
number_of_stddev     = 3
convergence          = 10e-5
