[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file         = "geometry/SPS_Nov_2022/aligned_dut_OPAMP_@RunNumber@_2.conf"		
detectors_file_updated = "geometry/SPS_Nov_2022/aligned_dut_OPAMP_@RunNumber@_3.conf"		
histogram_file         = "aligned-dut-OPAMP_@RunNumber@_3_threshold_seed5.5.root"
number_of_events = @NumberOfEvents@
output_directory="output/SPS_Nov_Physics/run@RunNumber@/"	

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
n_samples_baseline_opamp = 96		#OPAMP DAQ
minimum_sampling_frame_opamp = 98	#OPAMP DAQ
maximum_sampling_frame_opamp = 101	#OPAMP DAQ
n_samples_baseline_scope_opamp = 100 #OPAMP SCOPE number of points on which compute the baseline
n_signal_samples_scope_opamp = 50 #OPAMP SCOPE
shifting_from_t0 = 700
delay_from_t0 = 850
threshold_cut_t0_finder = 7
n_points_t0_finder = 10

[ClusteringSpatial]
type="ALPIDE"
use_trigger_timestamp=false 
charge_weighting=true
reject_by_roi=true 


[ClusteringAnalog]
type="OPAMP"
threshold_seed=5.5
threshold_neighbor=5.5
method="cluster"
seeding_method=max

[Correlations]

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 1mm,1mm
min_hits_on_track    = 6
exclude_dut          = true
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_5", "ALPIDE_6", "ALPIDE_7"
momentum             = 120GeV
unique_cluster_usage = true  # only use a cluster for one track. In case of multiple assignment, the track with the best chi2/ndof is kept. Default to falsed
reject_by_roi        = true
max_plot_chi2        = 100    # default to 50

[DUTAssociation]
type=			"OPAMP"
spatial_cut_abs=	10um,10um
time_cut_abs=		1e99

[AlignmentDUTResidual]
type=			"OPAMP"
align_orientation=	true
align_position_axes=	xy
align_position=		true
align_orientation_axes=	z
iterations=		3
max_track_chi2ndof = 	3
prune_tracks = 	true
