[Corryvreckan]
log_level  = "WARNING"


detectors_file         = "geometry/SPS_Nov_2022/aligned_dut_OPAMP_@RunNumber@_3.conf"		

histogram_file         = "Analyse_@RunNumber@.root"
number_of_events = @NumberOfEvents@
output_directory="output/SPS_Nov_Physics/run@RunNumber@/" 

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
n_samples_baseline_opamp = 96		#OPAMP DAQ
minimum_sampling_frame_opamp = 98	#OPAMP DAQ
maximum_sampling_frame_opamp = 101	#OPAMP DAQ
n_samples_baseline_scope_opamp = 100 #OPAMP SCOPE number of points on which compute the baseline
n_signal_samples_scope_opamp = 50 #OPAMP SCOPE
shifting_from_t0 = 700
delay_from_t0 = 850
threshold_cut_t0_finder = 7
n_points_t0_finder = 10

[ClusteringSpatial]
type = "ALPIDE"
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = true

[ClusteringAnalog]
type="OPAMP"
threshold_seed=5.5
threshold_neighbor=5.5
method="cluster"
seeding_method=max

[Correlations]

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 1mm,1mm
min_hits_on_track    = 6
exclude_dut          = true
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_5", "ALPIDE_6", "ALPIDE_7"
momentum             = 120GeV
unique_cluster_usage = true  # only use a cluster for one track. In case of multiple assignment, the track with the best chi2/ndof is kept. Default to falsed
reject_by_roi        = true
max_plot_chi2        = 100    # default to 50

[FilterEvents]
max_tracks = 1

[FilterEventsByIntercept]
type = "OPAMP"
boundary_track_intercept = [[0.5,0.5],[1.5,0.5],[1.5,2.5],[0.5,2.5]]

[DUTAssociation]
time_cut_abs    = 1e99               # no time cut
spatial_cut_abs = 15um,15um      # specifies a set of absolute values (x,y) which defines an ellipse for the maximum spatial distance in the xy plane between clusters and a track for association to the track
use_cluster_centre = true            # if true, the cluster centre will be compared to the track position for the spatial cut. If false, the nearest pixel in the cluster will be used. Defaults to false

[AnalysisDUT]
time_cut_frameedge       = 1000s
spatial_cut_sensoredge   = 0.5 #1    # parameter to discard telescope tracks at the sensor edges in fractions of pixel pitch. Default 0.5
chi2ndof_cut             = 5     # default value for 3
n_time_bins              = 1000  # number of bins in the time residual and correlation histograms. Default to 20000
time_binning             = 0.1ns # bin width in the time residual and correlation histograms. Default to 0.1ns.
correlations             = true  # creates correlation plots between all tracks and clusters on the DUT. Defaults to false.
file_name = "@DataDir@/run@RunNumber@.raw"
rune_tracks		= true
use_closest_cluster = true
inpixel_bin_size         = 0.5um  


# [AnalysisEfficiency]
# time_cut_frameedge       = 1000s
# chi2ndof_cut             = 5          # default to 3
# prune_tracks = true
# n_time_bins              = 1000       # number of bins in the time residual and correlation histograms. Default to 20000
# inpixel_bin_size         = 1um     # bin size of the in-pixel 2D efficiency histogram. Default to 1.0um
# inpixel_cut_edge         = 0um, 0um   # exclude tracks going within a cut-distance to the pixel edge. Effectively defines an in-pixel ROI. Default to 5um.
# spatial_cut_sensoredge   = 1
# use_closest_cluster = true
