[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2023-10_PS_3REF-MOSS-3REF_top.conf"
detectors_file_updated = ""    # external file provided by run_alignment_babymoss_oct.sh file
histogram_file         = "maskcreation_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = ""

[MaskCreator]
frequency_cut=1000
write_new_config=true
