[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file = "../../geometry/2022-07_PS_2REF-2DPTS-3REF_masked.conf"
detectors_file_updated = "../../geometry/2022-07_PS_2REF-2DPTS-3REF_prealigned.conf"
histogram_file = "prealignment_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
#file_name = "../data/run455090307_221111090319.raw"
train_time_cut_low_ch0=1500
train_time_cut_high_ch0=3000
train_time_cut_low_ch1=1500
train_time_cut_high_ch1=3000

[Clustering4D]
time_cut_abs=10s
charge_weighting=true
reject_by_roi=true

[Correlations]
do_time_cut=false

[Prealignment]
method = gauss_fit
fit_range_rel = 200
max_correlation_rms=6mm
time_cut_abs = 1e99