[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "" # external variable provided via make_scripts4run.sh; also check README.md
detectors_file_updated = "" # external variable provided via make_scripts4run.sh; also check README.md
histogram_file         = "" # external variable provided via make_scripts4run.sh; also check README.md 
number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "" # external variable provided via make_scripts4run.sh; also check README.md

[MaskCreator]
frequency_cut=1000
write_new_config=true