[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"


detectors_file         = "geometry/@IdealDetector@"
detectors_file_updated = "geometry/SPS_June_2023/prealigned_@RunNumber@.conf" 
histogram_file         = "prealignment_@RunNumber@.root"
number_of_events = @NumberOfEvents@
output_directory="output/SPS_June_2023_Physics/run@RunNumber@/"

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
sample_baseline = 96 		#APTS  
minimum_sampling_frame = 98		#APTS  
maximum_sampling_frame = 101		#APTS  
n_signal_samples_after_min = 0		#APTS
n_signal_samples_before_min = 0		#APTS
sample_baseline_opamp = 96		#OPAMP DAQ
first_sample_minimum_finder_opamp = 98	#OPAMP DAQ
last_sample_minimum_finder_opamp = 101	#OPAMP DAQ
n_samples_baseline_opamp_scope = 100 #OPAMP SCOPE number of points on which compute the baseline
n_samples_signal_opamp_scope = 100 #OPAMP SCOPE
baseline_shifting_from_t0_opamp_scope = 700
underline_delay_from_t0_opamp_scope = 600
threshold_cut_t0_finder_opamp_scope = 1120 #ADCu
n_points_t0_finder_opamp_scope = 700 #N integration points
osc_first_sample = 0
scope_ch1 = 5
scope_ch2 = 6
scope_ch3 = 9


[ClusteringSpatial]
type = "ALPIDE"
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = true

[ClusteringAnalog]
type="OPAMP"
threshold_seed=150
threshold_neighbor=150
method="cluster"
seeding_method=max

[ClusteringAnalog]
type="APTS"
threshold_seed=130
threshold_neighbor=130
method="cluster"
seeding_method=max

[Correlations]

[Prealignment]
damping_factor=1
method = gauss_fit
fit_range_rel = 50 
max_correlation_rms=6mm
time_cut_abs = 1e99