[Corryvreckan]
log_level  = "WARNING"

detectors_file         = "geometry/SPS_June_2023/aligned_dut_OPAMP_@RunNumber@_3.conf" 
detectors_file_updated = "geometry/SPS_June_2023/Eta_correction_@RunNumber@_3.conf"
histogram_file         = "Compute_eta_@RunNumber@.root"
number_of_events = @NumberOfEvents@
output_directory = "output/SPS_June_2023_Physics/run@RunNumber@/"


[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
sample_baseline = 96 		#APTS  
minimum_sampling_frame = 98		#APTS  
maximum_sampling_frame = 101		#APTS  
n_signal_samples_after_min = 0		#APTS
n_signal_samples_before_min = 0		#APTS
sample_baseline_opamp = 96		#OPAMP DAQ
first_sample_minimum_finder_opamp = 98	#OPAMP DAQ
last_sample_minimum_finder_opamp = 101	#OPAMP DAQ
n_samples_baseline_opamp_scope = 100 #OPAMP SCOPE number of points on which compute the baseline
n_samples_signal_opamp_scope = 100 #OPAMP SCOPE
baseline_shifting_from_t0_opamp_scope = 700
underline_delay_from_t0_opamp_scope = 600
threshold_cut_t0_finder_opamp_scope = 1120 #ADCu
n_points_t0_finder_opamp_scope = 700 #N integration points
osc_first_sample = 0
check_LGAD_signal = false
scope_ch1 = 5
scope_ch2 = 6
scope_ch3 = 9

[ClusteringSpatial]
type = "ALPIDE"
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = true

[ClusteringAnalog]
type="APTS"
threshold_seed=130
threshold_neighbor=130
method="cluster"
seeding_method=max

[ClusteringAnalog]
type="OPAMP"
threshold_seed=@ThresholdValue@
threshold_neighbor=@ThresholdValue@
method="cluster"
seeding_method=max

[Correlations]

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 1mm,1mm
min_hits_on_track    = 7
exclude_dut          = true
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_5", "ALPIDE_6", "ALPIDE_7","APTS_4"
momentum             = 120GeV
unique_cluster_usage = true  # only use a cluster for one track. In case of multiple assignment, the track with the best chi2/ndof is kept. Default to falsed
reject_by_roi        = true
max_plot_chi2        = 100    # default to 50


[DUTAssociation]
time_cut_abs    = 1e99               # no time cut
spatial_cut_abs = 15um,15um      # specifies a set of absolute values (x,y) which defines an ellipse for the maximum spatial distance in the xy plane between clusters and a track for association to the track
use_cluster_centre = true        # if true, the cluster centre will be compared to the track position for the spatial cut. If false, the nearest pixel in the cluster will be used. Defaults to false

[EtaCalculation]
log_level  = "INFO"
type="OPAMP"
eta_formula_x = "[0] + [1]*x + [2]*x^2 + [3]*x^3"
eta_formula_y = "[0] + [1]*x + [2]*x^2 + [3]*x^3"

