[Corryvreckan]
log_level  = "WARNING"


detectors_file         = "geometry/SPS_June_2023/aligned_dut_OPAMP_@RunNumber@_3.conf"
histogram_file         = "Noise_@RunNumber@_ADC.root"
number_of_events = @NumberOfEvents@
output_directory="output/SPS_June_2023_Physics/run@RunNumber@/" 

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
sample_baseline = 96 		#APTS  
minimum_sampling_frame = 98		#APTS  
maximum_sampling_frame = 101		#APTS  
n_signal_samples_after_min = 0		#APTS
n_signal_samples_before_min = 0		#APTS
sample_baseline_opamp = 96		#OPAMP DAQ
first_sample_minimum_finder_opamp = 98	#OPAMP DAQ
last_sample_minimum_finder_opamp = 101	#OPAMP DAQ
n_samples_baseline_opamp_scope = 100 #OPAMP SCOPE number of points on which compute the baseline
n_samples_signal_opamp_scope = 100 #OPAMP SCOPE
baseline_shifting_from_t0_opamp_scope = 700
underline_delay_from_t0_opamp_scope = 600
threshold_cut_t0_finder_opamp_scope = 1120 #ADCu
n_points_t0_finder_opamp_scope = 700 #N integration points
osc_first_sample = 0 #ok for the acquisition with sequence, use 23 for the single acquisition
check_LGAD_signal = false
noise_t0_sample_scope=3000
estimate_noise_scope=false
estimate_noise_daq=true
scope_ch1 = 5
scope_ch2 = 6
scope_ch3 = 9



