[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_prealigned.conf"
detectors_file_updated = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_aligned.conf"
histogram_file         = "alignment_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
# file_name = "../data/run484233616_211202233631.raw"
train_time_cut_low_ch0=500
train_time_cut_high_ch0=2000
train_time_cut_low_ch1=500
train_time_cut_high_ch1=2000


[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=false

[Correlations]

[Tracking4D]
track_model="straightline"
require_detectors=ALPIDE_0,ALPIDE_1,ALPIDE_2,DPTS_7,DPTS_6,ALPIDE_3,ALPIDE_4,ALPIDE_5
min_hits_on_track=8
time_cut_abs=1e99
momentum=10GeV
exclude_dut = false
spatial_cut_abs=1mm,1mm
reject_by_roi=false

[AlignmentMillepede]
residual_cut = 0.05mm
residual_cut_init = 1mm
iterations = 3
dofs = true, true, false, false, false, true
sigmas = 50um, 50um, 50um, 0.005rad, 0.005rad, 0.005rad
exclude_dut = false
number_of_stddev = 0
convergence = 10e-5
