[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2022-05_PS_3REF-2DPTS-3REF.conf"
detectors_file_updated = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_masked.conf"
histogram_file         = "maskcreation_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
# file_name = "../data/run484233616_211202233631.raw"
train_time_cut_low_ch0=500
train_time_cut_high_ch0=2000
train_time_cut_low_ch1=500
train_time_cut_high_ch1=2000

[MaskCreator]
frequency_cut=5000