[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF_prealigned.conf"
detectors_file_updated = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF_trackingplanes_aligned.conf"
histogram_file         = "alignment_trackingplanes_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
eudaq_loglevel = WARN
file_name = "../data/run365155753_210910160123.raw"
train_time_cut_low_ch0 = 500.0
train_time_cut_high_ch0 = 2000.0
train_time_cut_low_ch1 = 500.0
train_time_cut_high_ch1 = 2000.0

[Clustering4D]
time_cut_abs     = 10s
charge_weighting = true
reject_by_roi    = true

[Correlations]

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 150um,150um
min_hits_on_track    = 6
exclude_dut          = true
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_5", "ALPIDE_6", "ALPIDE_7"
momentum             = 5.4GeV
unique_cluster_usage = false
reject_by_roi        = true
max_plot_chi2        = 100

[FilterEvents]
max_tracks = 1

[AlignmentMillepede]
residual_cut         = 0.05mm
residual_cut_init    = 1mm
iterations           = 3
dofs                 = true, true, false, false, false, true
sigmas               = 50um, 50um, 50um, 0.005rad, 0.005rad, 0.005rad
exclude_dut          = true
number_of_stddev     = 0
convergence          = 10e-5
