[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF_dut_aligned.conf"
histogram_file = "analysis_run_test.root"
number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../data/run365155753_210910160123.raw"

[Clustering4D]
time_cut_abs     = 10s
charge_weighting = true
reject_by_roi    = true

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 150um,150um
min_hits_on_track    = 6
exclude_dut          = true
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_5", "ALPIDE_6", "ALPIDE_7" 
momentum             = 5.4GeV
unique_cluster_usage = false
reject_by_roi        = false
max_plot_chi2        = 100

[FilterEvents]
max_tracks = 1

[DUTAssociation]
time_cut_abs       = 1e99
spatial_cut_abs    = 45um,45um
use_cluster_centre = true

[AnalysisDUT]
time_cut_frameedge     = 1000s
spatial_cut_sensoredge = 2
chi2ndof_cut           = 3
inpixel_bin_size       = 1.0um
n_time_bins            = 1000
time_binning           = 0.1ns
correlations           = true