[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF.conf"
detectors_file_updated = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF_masked.conf"
histogram_file         = "maskcreation_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
eudaq_loglevel = WARN
file_name = "../data/run365155753_210910160123.raw"
train_time_cut_low_ch0 = 500.0
train_time_cut_high_ch0 = 2000.0
train_time_cut_low_ch1 = 500.0
train_time_cut_high_ch1 = 2000.0

[MaskCreator]
frequency_cut=1000
