[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF_masked.conf"
detectors_file_updated = "../../geometry/2021-09_DESY_3REF-2DPTS-3REF_prealigned.conf"
histogram_file         = "prealignment_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
eudaq_loglevel = WARN
file_name = "../data/run365155753_210910160123.raw"
train_time_cut_low_ch0 = 500.0
train_time_cut_high_ch0 = 2000.0
train_time_cut_low_ch1 = 500.0
train_time_cut_high_ch1 = 2000.0

[Clustering4D]
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = true

[Correlations]

[Prealignment]
damping_factor=1
method = gauss_fit
fit_range_rel = 20
max_correlation_rms=6mm
time_cut_abs = 1e99
