[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file= ""
histogram_file = ""

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
eudaq_loglevel="INFO"
file_name = ""
train_time_cut_low_ch0=1500
train_time_cut_high_ch0=3000
train_time_cut_low_ch1=1500
train_time_cut_high_ch1=3000
include_bad_trains=1 # for efficiency
#include_bad_trains=0 # for spatial resolution, but in this case as we are computing the in-pixel efficiency I keep this one!

[Clustering4D]
time_cut_abs     = 10s
charge_weighting = true  # if true, calculate a charge-weighted mean for the cluster centre. If false, calculate the simple arithmetic mean. Default to true
reject_by_roi    = true

[Correlations]
do_time_cut=false

[Tracking4D]
track_model          = "gbl"
time_cut_abs         = 1e99
spatial_cut_abs      = 1mm,1mm
min_hits_on_track    = 6
exclude_dut          = true
require_detectors    = "ALPIDE_0", "ALPIDE_1", "ALPIDE_2", "ALPIDE_3", "ALPIDE_4", "ALPIDE_5"
momentum             = 3.4GeV
unique_cluster_usage = true  # only use a cluster for one track. In case of multiple assignment, the track with the best chi2/ndof is kept. Default to falsed
reject_by_roi        = true
max_plot_chi2        = 100

[FilterEvents]
max_tracks=1

[DUTAssociation]
spatial_cut_abs=480um,480um # for efficiency
#spatial_cut_abs=45um,45um # for spatial resolution
time_cut_abs=1e99
use_cluster_centre = true

[AnalysisDUT]
chi2ndof_cut=3
n_time_bins = 200
spatial_cut_sensoredge=2

[AnalysisEfficiency]
chi2ndof_cut=3
inpixel_bin_size=1um
inpixel_cut_edge=0um,0um
spatial_cut_sensoredge=2
