[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file = ""
detectors_file_updated = ""
histogram_file = ""

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = ""
train_time_cut_low_ch0=1500
train_time_cut_high_ch0=3000
train_time_cut_low_ch1=1500
train_time_cut_high_ch1=3000

[MaskCreator]
frequency_cut=1000
