[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file         = "geometry/APTS_REFERENCE_RUN/aligned_@RunNumber@_NEW_ALPIDE_thr5.5.conf"

detectors_file_updated = "geometry/APTS_REFERENCE_RUN/aligned-dut-APTS_@RunNumber@_NEW_1_APTS_ONLY_thr5.5.conf"

histogram_file         = "align-1-dut-APTS-ONLY_@RunNumber@.root"
number_of_events = @NumberOfEvents@

output_directory="output/run@RunNumber@/"


[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
sample_baseline = 14 		#APTS  96
minimum_sampling_frame = 18		#APTS  98
maximum_sampling_frame = 21		#APTS  101
n_signal_samples_after_min = 0		#APTS
n_signal_samples_before_min = 0		#APTS
sample_baseline_opamp = 96		#OPAMP DAQ
first_sample_minimum_finder_opamp = 98	#OPAMP DAQ
last_sample_minimum_finder_opamp = 101	#OPAMP DAQ
n_samples_baseline_opamp_scope = 100 #OPAMP SCOPE number of points on which compute the baseline
n_samples_signal_opamp_scope = 50 #OPAMP SCOPE
baseline_shifting_from_t0_opamp_scope = 700
underline_delay_from_t0_opamp_scope = 850
threshold_cut_t0_finder_opamp_scope = 7
n_points_t0_finder_opamp_scope = 10

[ClusteringSpatial]
type="ALPIDE"
use_trigger_timestamp=false 
charge_weighting=true
reject_by_roi=true 

[ClusteringAnalog]
type="APTS"
threshold_seed=125
threshold_neighbor=125
method="cluster"
seeding_method=max

[ClusteringAnalog]
type="OPAMP"
threshold_seed=5.5
threshold_neighbor=5.5
method="cluster"
seeding_method=max

[Correlations]

[Tracking4D]
track_model=		"gbl"
require_detectors=	ALPIDE_0,ALPIDE_1,ALPIDE_2,ALPIDE_7,ALPIDE_8,ALPIDE_9
min_hits_on_track=	6 #number of planes that I have, ok
time_cut_abs=		1e99
momentum=		120.0GeV
exclude_dut = 		true
spatial_cut_abs=	1mm,1mm
reject_by_roi=		true
unique_cluster_usage = true

#[FilterEvents]
#max_tracks =1

[DUTAssociation]
type=			"APTS"
spatial_cut_abs=	100um,100um
time_cut_abs=		1e99

[AlignmentDUTResidual]
type=			"APTS"
align_orientation=	false
align_position_axes=	xy
align_position=		true
align_orientation_axes=	z
iterations=		3
max_track_chi2ndof = 	3
prune_tracks = 	true
