[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "geometry/@IdealDetector@"
detectors_file_updated = "geometry/masked_@RunNumber@.conf"
histogram_file         = "masking_@RunNumber@.root"
number_of_events = @NumberOfEvents@
output_directory="output/run@RunNumber@/"

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@DataDir@/run@RunNumber@.raw"
sample_baseline = 14 		#APTS  96
minimum_sampling_frame = 18		#APTS  98
maximum_sampling_frame = 21		#APTS  101
n_signal_samples_after_min = 0		#APTS
n_signal_samples_before_min = 0		#APTS
sample_baseline_opamp = 96		#OPAMP DAQ
first_sample_minimum_finder_opamp = 98	#OPAMP DAQ
last_sample_minimum_finder_opamp = 101	#OPAMP DAQ
n_samples_baseline_opamp_scope = 100 #OPAMP SCOPE number of points on which compute the baseline
n_samples_signal_opamp_scope = 50 #OPAMP SCOPE
baseline_shifting_from_t0_opamp_scope = 700
underline_delay_from_t0_opamp_scope = 850
threshold_cut_t0_finder_opamp_scope = 7
n_points_t0_finder_opamp_scope = 10

[MaskCreator]
type=ALPIDE
frequency_cut=10000 # for APTS trigger runs
