[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file = "../../geometry/2021-11_SPS_3REF-2DPTS-3REF_aligned.conf"
histogram_file = "analysis_run_test.root"

# detectors_file = "geometry/aligned_@ReferenceRun@.conf"
# histogram_file = "analysis_@RunNumber@.root"
# number_of_events = @NumberOfEvents@
number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../data/run484233616_211202233631.raw"
# file_name = "@DataDir@/run@RunNumber@.raw"
train_time_cut_low_ch0=500
train_time_cut_high_ch0=2000
train_time_cut_low_ch1=500
train_time_cut_high_ch1=2000

[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=true

[Correlations]

[Tracking4D]
track_model="straightline"
require_detectors=ALPIDE_0,ALPIDE_1,ALPIDE_2,ALPIDE_3,ALPIDE_4,ALPIDE_5
time_cut_abs=10s
spatial_cut_abs=150um,150um
min_hits_on_track=6
exclude_dut=true
momentum = 120GeV
volume_scattering = false
volume_radiation_length = 304.2m
reject_by_roi=true

# comment out for residuals analysis
[FilterEvents]
max_tracks=1

# [AnalysisTracks]

[DUTAssociation]
spatial_cut_abs=500um,500um
time_cut_abs=1e99

[AnalysisDUT]
time_cut_frameedge=20ns
chi2ndof_cut=3
use_closest_cluster=true
n_time_bins = 200
spatial_cut_sensoredge=3

[AnalysisEfficiency]
time_cut_frameedge=20ns
chi2ndof_cut=3
inpixel_bin_size=1um
spatial_cut_sensoredge=3

