[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2021-11_SPS_3REF-2DPTS-3REF.conf"
detectors_file_updated = "../../geometry/2021-11_SPS_3REF-2DPTS-3REF_masked.conf"
histogram_file         = "maskcreation_run_test.root"

# detectors_file         = "geometry/@IdealDetector@"
# detectors_file_updated = "geometry/masked_@RunNumber@.conf"
# histogram_file         = "maskcreation_@RunNumber@.root"
# number_of_events = @NumberOfEvents@

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../data/run484233616_211202233631.raw"
# file_name = "@DataDir@/run@RunNumber@.raw"
train_time_cut_low_ch0=500
train_time_cut_high_ch0=2000
train_time_cut_low_ch1=500
train_time_cut_high_ch1=2000

[MaskCreator]
frequency_cut=1000