[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "/local/geometry/3REF-X0-3REF.conf"
detectors_file_updated = "/local/geometry/monitor_run@RunNumber@.conf"
histogram_file         = "monitor_run@RunNumber@.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../data/run363230028_210908234924.raw"
# file_name = "../data/run@RunNumber@.raw"
long_detector_id=true

[MaskCreator]
frequency_cut=100

[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=false

[Correlations]

[Tracking4D]
track_model="gbl"
min_hits_on_track=7
require_detectors=ALPIDE_0,ALPIDE_1,ALPIDE_2,ALPIDE_3,ALPIDE_4,ALPIDE_5,ALPIDE_6
exclude_dut = false
spatial_cut_abs=100um,100um
momentum=5.4GeV
reject_by_roi=false
time_cut_abs = 1e99

[OnlineMonitor]
update = 1000
clustering_module = "ClusteringSpatial"
dut_plots = [["EventLoaderEUDAQ2/%DETECTOR%/hitmap", "colz"],["ClusteringSpatial/%DETECTOR%/clusterSize"],["Tracking4D/trackChi2ndof"]]