
[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file =  ""
histogram_file = ""

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = ""
# Here the most common train time cut values, to know the values for each setting see
# https://indico.cern.ch/event/1293487/contributions/5438206/attachments/2660321/4608454/WP3_06062023_CutOnTime.pdf
train_time_cut_low_ch0=1000
train_time_cut_high_ch0=4000
train_time_cut_low_ch1=1000
train_time_cut_high_ch1=4000

[MaskCreator]
frequency_cut=1000
