[Corryvreckan]
detectors_file = "@Pwd@/@GeometryFile@"
log_level = "ERROR"
log_format = "DEFAULT"
detectors_file_updated = "@Pwd@/geometry_updated/masked_@RunNumber@.conf"
histogram_file = "maskcreation_@RunNumber@.root"
number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "@Pwd@/@DataDir@/@RunNumber@"
type = ALPIDE

[EventLoaderEUDAQ2]
file_name = "@Pwd@/@DataDir@/@RunNumber@"
sample_baseline = 96 #(default:0) Sample used to calculate the baseline
n_signal_samples_after_min = 0 #(default:0)  Number of samples for signal extraction after minimum. Signal minimum always included
n_signal_samples_before_min = 0 #(default:0) Number of samples for signal extraction before minimum
minimum_sampling_frame=98
maximum_sampling_frame=101
type = APTS

[MaskCreator]
method = frequency
frequency_cut = 10000
write_new_config = true
