[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_aligned.conf"
histogram_file = "analysis_run_test.root"
number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../../data/rate-test/run212171708_220524171714.raw"
# file_name = "../../data/rate-test/run212173603_220524173609.raw"


[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=false

[Correlations]

[Tracking4D]
track_model="gbl"
require_detectors=ALPIDE_0,ALPIDE_1,ALPIDE_2,ALPIDE_3,ALPIDE_4,ALPIDE_5
time_cut_abs=10s
spatial_cut_abs=150um,150um #1mm,1mm or 5mm,5mm
min_hits_on_track=6
exclude_dut=true
momentum = 10GeV
volume_scattering = false
volume_radiation_length = 304.2m
reject_by_roi=false
unique_cluster_usage=true

[AnalysisTracks]

