[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_rate.conf"
detectors_file_updated = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_masked.conf"
histogram_file         = "maskcreation_run_test.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../../data/rate-test/run212171940_220524171946.raw"
# file_name = "../../data/rate-test/run212173603_220524173609.raw"


[MaskCreator]
frequency_cut=2000