[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_masked.conf"
detectors_file_updated = "../../geometry/2022-05_PS_3REF-2DPTS-3REF_prealigned.conf"
histogram_file         = "prealignment_run_test.root"

number_of_events = 1000

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../../data/rate-test/run212171708_220524171714.raw"
# file_name = "../../data/rate-test/run212173603_220524173609.raw"

[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=false

[Correlations]

[Prealignment]
damping_factor=1
max_correlation_rms=6mm
method=gauss_fit
fit_range_rel=100
time_cut_abs=1e99
