[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file         = "../../geometry/2023-07_PS_3REF-MOSS-3REF_masked.conf"
detectors_file_updated = "../../geometry/2023-07_PS_3REF-MOSS-3REF_prealigned.conf"
histogram_file         = "prealignment_run_test_t6_july.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../../data/2023-07_PS/vcasb_scan_region2/run291180334_230718072806.raw"

[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=false

[Correlations]

[Prealignment]
damping_factor=1
max_correlation_rms=6mm
method=gauss_fit
fit_range_rel=50
time_cut_abs=1e99
