[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file         = "../geometry/3REF-X0-3REF.conf"
detectors_file_updated = "../geometry/masked_run@RunNumber@.conf"
histogram_file         = "masked_run@RunNumber@.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../data/run@RunNumber@.raw"

[MaskCreator]
frequency_cut=100
