[Corryvreckan]
log_level  = "WARNING"
log_format = "DEFAULT"

detectors_file         = "../geometry/aligned2_run@RunNumber@.conf"
detectors_file_updated = "../geometry/analysis_run@RunNumber@.conf"
histogram_file         = "analysis_run@RunNumber@.root"

number_of_events = -1

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
file_name = "../data/run@RunNumber@.raw"

[ClusteringSpatial]
use_trigger_timestamp=false
charge_weighting=true
reject_by_roi=false

[TrackingMultiplet]
scatterer_position=3mm
upstream_detectors=ALPIDE_0,ALPIDE_1,ALPIDE_2
downstream_detectors=ALPIDE_4,ALPIDE_5,ALPIDE_6
min_hits_upstream=3
min_hits_downstream=3
isolation_cut=0
scatterer_matching_cut = 1mm
time_cut_abs=10s
spatial_cut_abs = 1mm, 1mm
track_model="straightline"
momentum=5.4GeV

[AnalysisMaterialBudget]
image_size = 30mm 15mm
cell_size = 50um 50um
angle_cut = 100mrad
quantile = 0.9
min_cell_content = 5
update = false